fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "test@test.com%"
        sender_name: "test"
    resetting:
        email:
            template:   :emails:password_resetting.email.twig
